# Generated by Django 5.2.8 on 2026-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_multa_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario Normal'), ('bodeguero', 'Bodeguero'), ('bibliotecario', 'Bibliotecario'), ('admin', 'Administrador'), ('superusuario', 'Superusuario')], default='usuario', max_length=20),
        ),
    ]
