# Generated by Django 5.2.8 on 2026-01-07 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_libro_imagen_alter_libro_titulo_solicitudprestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('registro', 'Registro de Usuario'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver/Consultar'), ('solicitud', 'Solicitud de Préstamo'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar'), ('devolucion', 'Devolución'), ('pago', 'Pago de Multa'), ('otro', 'Otra Acción')], max_length=20)),
                ('descripcion', models.TextField()),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
