# Generated by Django 5.2.8 on 2026-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_registroactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
