# Generated by Django 5.2.8 on 2026-01-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_libro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='es_de_openlibrary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
