# Generated by Django 6.0.1 on 2026-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_libro_en_odoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
