# Generated by Django 6.0.1 on 2026-01-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_libro_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen',
        ),
    ]
